version: "3.8"
services:
    app:
        container_name: python_app
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: dockerize -wait tcp://db:55432 -timeout 20s ./.docker/entrypoint.sh
        volumes:
            - .:/app
        environment:
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
            - DEBUG=1
            - HOST=0.0.0.0
        depends_on:
            - db
        networks:
            - python-app-network
    db:
        container_name: postgres_db
        image: postgres:13.2-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
        volumes:
            - .docker/dbdata:/var/lib/postgresql/data
        ports:
            - 55432:5432
        networks:
            - python-app-network

networks:
    python-app-network:
        driver: bridge
