version: "3.8"
services:
    app:
        container_name: python_app
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        volumes:
            - ./app:/app
        environment:
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
            - DEBUG=1
            - HOST=0.0.0.0
        networks:
            - python-app-network

networks:
    python-app-network:
        driver: bridge
